FOREGROUND_THRESHOLD = .5
IMG_PATCH_SIZE = 16
NUM_CHANNELS = 3
NUM_LABELS = 2
PIXEL_DEPTH = 255
IMAGE_WIDTH = 400
IMAGE_HEIGHT = 400
PATCHES_PER_IMAGE = int((IMAGE_WIDTH / IMG_PATCH_SIZE) * (IMAGE_HEIGHT / IMG_PATCH_SIZE))
